-- Create database
CREATE DATABASE IF NOT EXISTS recsys;
USE recsys;

-- Create tables
CREATE TABLE IF NOT EXISTS user (
    uid INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS FOLLOW (
    XID INT,
    YID INT,
    FOREIGN KEY (XID) REFERENCES user(uid),
    FOREIGN KEY (YID) REFERENCES user(uid),
    CONSTRAINT chk_XID_YID_diff CHECK (XID <> YID)
);

CREATE TABLE IF NOT EXISTS LANGUAGES (
    LID INT AUTO_INCREMENT PRIMARY KEY,
    LANGUAGE VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS GENRES (
    GID INT AUTO_INCREMENT PRIMARY KEY,
    GENRE VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS MOVIES (
    MID INT AUTO_INCREMENT PRIMARY KEY,
    MOVIE VARCHAR(255) NOT NULL UNIQUE,
    LID INT,
    FOREIGN KEY (LID) REFERENCES LANGUAGES(LID)
);

CREATE TABLE IF NOT EXISTS BOOKS (
    BID INT AUTO_INCREMENT PRIMARY KEY,
    BOOK VARCHAR(255) NOT NULL UNIQUE,
    LID INT,
    FOREIGN KEY (LID) REFERENCES LANGUAGES(LID)
);

CREATE TABLE IF NOT EXISTS TVSHOWS (
    TVID INT AUTO_INCREMENT PRIMARY KEY,
    TVSHOW VARCHAR(255) NOT NULL UNIQUE,
    LID INT,
    FOREIGN KEY (LID) REFERENCES LANGUAGES(LID)
);

CREATE TABLE IF NOT EXISTS MOVIES_GENRES (
    MID INT,
    GID INT,
    FOREIGN KEY (MID) REFERENCES MOVIES(MID),
    FOREIGN KEY (GID) REFERENCES GENRES(GID),
    PRIMARY KEY (MID, GID)
);

CREATE TABLE IF NOT EXISTS BOOKS_GENRES (
    BID INT,
    GID INT,
    FOREIGN KEY (BID) REFERENCES BOOKS(BID),
    FOREIGN KEY (GID) REFERENCES GENRES(GID),
    PRIMARY KEY (BID, GID)
);

CREATE TABLE IF NOT EXISTS TVSHOWS_GENRES (
    TVID INT,
    GID INT,
    FOREIGN KEY (TVID) REFERENCES TVSHOWS(TVID),
    FOREIGN KEY (GID) REFERENCES GENRES(GID),
    PRIMARY KEY (TVID, GID)
);

CREATE TABLE IF NOT EXISTS USER_MOVIE_LANG_PREF (
    UID INT,
    LID INT,
    FOREIGN KEY (UID) REFERENCES user(uid),
    FOREIGN KEY (LID) REFERENCES LANGUAGES(LID),
    PRIMARY KEY (UID, LID)
);

CREATE TABLE IF NOT EXISTS USER_BOOK_LANG_PREF (
    UID INT,
    LID INT,
    FOREIGN KEY (UID) REFERENCES user(uid),
    FOREIGN KEY (LID) REFERENCES LANGUAGES(LID),
    PRIMARY KEY (UID, LID)
);

CREATE TABLE IF NOT EXISTS USER_TVSHOW_LANG_PREF (
    UID INT,
    LID INT,
    FOREIGN KEY (UID) REFERENCES user(uid),
    FOREIGN KEY (LID) REFERENCES LANGUAGES(LID),
    PRIMARY KEY (UID, LID)
);

CREATE TABLE IF NOT EXISTS USER_MOVIE_GEN_PREF (
    UID INT,
    GID INT,
    FOREIGN KEY (UID) REFERENCES user(uid),
    FOREIGN KEY (GID) REFERENCES GENRES(GID),
    PRIMARY KEY (UID, GID)
);

CREATE TABLE IF NOT EXISTS USER_BOOK_GEN_PREF (
    UID INT,
    GID INT,
    FOREIGN KEY (UID) REFERENCES user(uid),
    FOREIGN KEY (GID) REFERENCES GENRES(GID),
    PRIMARY KEY (UID, GID)
);

CREATE TABLE IF NOT EXISTS USER_TVSHOW_GEN_PREF (
    UID INT,
    GID INT,
    FOREIGN KEY (UID) REFERENCES user(uid),
    FOREIGN KEY (GID) REFERENCES GENRES(GID),
    PRIMARY KEY (UID, GID)
);

CREATE TABLE IF NOT EXISTS USER_TVSHOW_WATCHED (
    UID INT,
    TVID INT,
    FOREIGN KEY (UID) REFERENCES user(uid),
    FOREIGN KEY (TVID) REFERENCES TVSHOWS(TVID),
    PRIMARY KEY (UID, TVID)
);

CREATE TABLE IF NOT EXISTS USER_MOVIE_WATCHED (
    UID INT,
    MID INT,
    FOREIGN KEY (UID) REFERENCES user(uid),
    FOREIGN KEY (MID) REFERENCES MOVIES(MID),
    PRIMARY KEY (UID, MID)
);

CREATE TABLE IF NOT EXISTS USER_BOOK_READ (
    UID INT,
    BID INT,
    FOREIGN KEY (UID) REFERENCES user(uid),
    FOREIGN KEY (BID) REFERENCES BOOKS(BID),
    PRIMARY KEY (UID, BID)
);
